/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 28 05:39:41 GMT 2017
 */

package org.cs362.dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.cs362.dominion.board;
import org.cs362.dominion.deck;
import org.cs362.dominion.great_hall;
import org.cs362.dominion.hand;
import org.cs362.dominion.player;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class great_hall_ESTest extends great_hall_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      player[] playerArray0 = new player[20];
      player player0 = new player();
      playerArray0[0] = player0;
      deck deck0 = new deck();
      deck0.num_cards = 0;
      player0.player_deck = deck0;
      great_hall great_hall0 = new great_hall();
      great_hall0.gold = (-1);
      board board0 = new board();
      board0.buy_curse(player0, board0);
      great_hall0.perform_attack(playerArray0, 0, board0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      player[] playerArray0 = new player[20];
      player player0 = new player();
      playerArray0[0] = player0;
      deck deck0 = new deck();
      deck0.num_cards = 0;
      player0.player_deck = deck0;
      great_hall great_hall0 = new great_hall();
      great_hall0.gold = (-1);
      board board0 = new board();
      // Undeclared exception!
      try { 
        great_hall0.perform_attack(playerArray0, 0, board0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         assertThrownBy("org.cs362.dominion.deck", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      player[] playerArray0 = new player[20];
      player player0 = new player();
      playerArray0[0] = player0;
      board board0 = new board();
      deck deck0 = new deck();
      deck0.num_cards = (-50);
      player0.player_deck = deck0;
      great_hall great_hall0 = new great_hall();
      // Undeclared exception!
      try { 
        great_hall0.perform_attack(playerArray0, 0, board0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -51
         //
         assertThrownBy("org.cs362.dominion.deck", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      player[] playerArray0 = new player[20];
      player player0 = new player();
      playerArray0[0] = player0;
      great_hall great_hall0 = new great_hall();
      great_hall0.gold = (-1);
      board board0 = new board();
      great_hall0.perform_attack(playerArray0, 0, board0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      player[] playerArray0 = new player[20];
      great_hall great_hall0 = new great_hall();
      board board0 = new board();
      // Undeclared exception!
      try { 
        great_hall0.perform_attack(playerArray0, (-1), board0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         assertThrownBy("org.cs362.dominion.great_hall", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      player[] playerArray0 = new player[20];
      great_hall great_hall0 = new great_hall();
      great_hall0.gold = (-1);
      board board0 = new board();
      // Undeclared exception!
      try { 
        great_hall0.perform_attack(playerArray0, 0, board0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.great_hall", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      great_hall great_hall0 = new great_hall();
      player[] playerArray0 = new player[10];
      player player0 = new player();
      hand hand0 = player0.player_hand;
      hand0.num_cards = (-1312);
      playerArray0[0] = player0;
      board board0 = new board();
      // Undeclared exception!
      try { 
        great_hall0.perform_attack(playerArray0, 0, board0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.hand", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      great_hall great_hall0 = new great_hall();
      great_hall0.description();
  }
}
