/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 27 07:59:17 GMT 2017
 */

package org.cs362.dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import org.cs362.dominion.Board;
import org.cs362.dominion.Mine;
import org.cs362.dominion.Player;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.TooManyResourcesException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Mine_ESTest extends Mine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Mine mine0 = new Mine();
      ArrayList<Player> arrayList0 = new ArrayList<Player>();
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        mine0.Action(arrayList0, (Player) null, board0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.Mine", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Mine mine0 = new Mine();
      ArrayList<Player> arrayList0 = new ArrayList<Player>();
      Player player0 = new Player("YMD", true);
      player0.addToHand(mine0);
      // Undeclared exception!
      try { 
        mine0.Action(arrayList0, player0, (Board) null);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Mine mine0 = new Mine();
      ArrayList<Player> arrayList0 = new ArrayList<Player>();
      Player player0 = new Player("^'bH", true);
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        mine0.Action(arrayList0, player0, board0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Mine mine0 = new Mine();
      ArrayList<Player> arrayList0 = new ArrayList<Player>();
      Player player0 = new Player("Mine", false);
      mine0.Action(arrayList0, player0, (Board) null);
      assertEquals(0, mine0.getTreasure());
  }
}
